- id: '4569875412547'
  alias: Home Assistant Start
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.temperature_slider
      value: '{{ states(''sensor.lyric_temperature_setting'') | int }}'
- id: '1504394346958'
  alias: Chris Arrive Work
  trigger:
  - entity_id: device_tracker.chris_galactiphone
    event: enter
    platform: zone
    zone: zone.work
  condition: []
  action:
  - data_template:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Chris arrived at Work
    service: notify.all_phones_message_only
- id: '1504394569874'
  alias: Chris Leave Work
  trigger:
  - entity_id: device_tracker.chris_galactiphone
    event: leave
    platform: zone
    zone: zone.work
  condition: []
  action:
  - data_template:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Chris left Work
    service: notify.all_phones_message_only
- id: '1504394346747'
  alias: Chris Arrive Home
  trigger:
  - entity_id: device_tracker.chris_galactiphone
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data_template:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Chris is Home
    service: notify.all_phones_message_only
- id: '1504394563412'
  alias: Chris Leave Home
  trigger:
  - entity_id: device_tracker.chris_galactiphone
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Chris left Home
    service: notify.html5_notifier_galactiphone
  - data:
      entity_id: lock.front_door_lock_locked
    service: lock.lock
- id: '1504399601993'
  alias: Jazzy Arrive Home
  trigger:
  - entity_id: device_tracker.jazzy_jazzymae
    event: enter
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data_template:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Jasmine is Home
    service: notify.all_phones_message_only
- id: '1504399601123'
  alias: Jazzy Leaves Home
  trigger:
  - entity_id: device_tracker.jazzy_jazzymae
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - data_template:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Jasmine left Home
    service: notify.all_phones_message_only
  - data:
      entity_id: lock.front_door_lock_locked
    service: lock.lock
- id: '1511302208019'
  alias: Holiday Sunset Events
  action:
  - data:
      event: christmas_tree_on
    service: ifttt.trigger
  - data:
      event: fire_place_lights_on
    service: ifttt.trigger
  - data:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Holiday Sunset Event Triggered
    service: notify.all_phones_message_only
  condition:
  - condition: state
    entity_id: group.phones_group
    state: home
  - condition: state
    entity_id: input_boolean.holiday_season
    state: 'on'
  trigger:
  - event: sunset
    offset: -01:00:00
    platform: sun
- id: '1511302332761'
  alias: Holiday Sunrise Event
  action:
  - data:
      event: christmas_tree_off
    service: ifttt.trigger
  - data:
      event: fire_place_lights_off
    service: ifttt.trigger
  - data:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Holiday Sunrise Event Triggered
    service: notify.all_phones_message_only
  condition:
  - condition: state
    entity_id: input_boolean.holiday_season
    state: 'on'
  trigger:
  - event: sunrise
    offset: +01:00:00
    platform: sun
- id: '1511359777645'
  alias: Notification Lock Request
  trigger:
  - event_data:
      action: lock_door
    event_type: html5_notification.clicked
    platform: event
  action:
  - service: lock.lock
    data:
      entity_id: lock.front_door_lock_locked
  - service: notify.all_phones_message_only
    data:
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
      message: Door lock command sent
  condition:
  - condition: state
    entity_id: lock.front_door_lock_locked
    state: unlocked
- id: '1511957477698'
  alias: Temp Slider Moved
  trigger:
    platform: state
    entity_id: input_number.temperature_slider
  action:
  - service: climate.set_temperature
    data_template:
      entity_id: climate.lyric_thermostat
      temperature: '{{ states(''input_number.temperature_slider'') | int }}'
- id: '2587951276548'
  alias: Temp Setting Changed
  trigger:
    platform: state
    entity_id: sensor.lyric_temperature_setting
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.temperature_slider
      value: '{{ states(''sensor.lyric_temperature_setting'') | int }}'
- id: '8524784598155'
  alias: Food Prep Notification
  trigger:
  - at: 08:00:00
    platform: time
  condition:
  - condition: state
    entity_id: sensor.meal_planned
    state: 'yes'
  action:
  - data_template:
      message: Pull out food to make {{states.sensor.next_meal.state}}
      title: '{{now().strftime("%Y-%m-%d %H:%M:%S")}}'
    service: notify.all_phones_message_only