homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 29.6760027
  longitude: -95.0851829
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 8
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  # Customize settings
  customize: !include customize.yaml
  customize_domain: !include customize_domain.yaml
  customize_glob: !include customize_glob.yaml
  
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: es5

# map
map:

# Enables configuration UI
config:
  

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: example.duckdns.org:8123
  
  trusted_networks:
    - 10.0.0.0/24
  base_url: homeassistant.redneckit.net

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true
  
# Discover some devices automatically
discovery:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.random_sensor
      - sensor.pws_feelslike_f
      - sensor.pws_heat_index_f
      - sensor.pws_location
      - sensor.pws_precip_today_in
      - sensor.pws_pressure_in
      - sensor.pws_temp_f
      - sensor.pws_weather_1h
      - sensor.pws_wind_dir
      - sensor.pws_wind_mph
      - sensor.time_to_home
      - sensor.time_to_work
      - sensor.work_home_duration
      - sensor.home_work_duration

# Control Logbook entries
logger:
  default: error

# Track the sun
sun:

# Adds Terminal to main page
#panel_iframe:
#  terminal:
#    title: Terminal
#    icon: mdi:console
#    url: https://10.0.0.94:7681

# Adds Configuration Editor to main page    
#  configurator:
#    title: Configuration Editor
#    icon: mdi:wrench
#    url: https://10.0.0.94:3218

# Text to speech
tts:
  - platform: google

# IFTTT
ifttt:
  key: !secret ifttt_key

# Google Calendar
google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret

# Google Domains
google_domains:
  domain: dyndns.redneckit.net
  username: !secret google_domains_username
  password: !secret google_domains_password
  
# Google Assistant
google_assistant:
  project_id: home-assistant-178722
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  api_key: !secret google_assistant_api_key
  expose_by_default: false

# USPS
#usps:
#  username: !secret usps_username
#  password: !secret usps_password
    
# MQTT
mqtt:
  broker: m13.cloudmqtt.com
  port: 11250
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password

# IOS App
ios:
  push:
    categories:
      - name: Alarm
        identifier: 'alarm'
        actions:
          - identifier: 'SOUND_ALARM'
            title: 'Lock Door'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'SILENCE_ALARM'
            title: 'Ignore'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
            
# Lyric
lyric:
  client_id: !secret lyric_client_id
  client_secret: !secret lyric_client_secret

# Other configurations to include
device_tracker: !include device_tracker.yaml
sensor: !include sensor.yaml
group: !include groups.yaml
automation: !include automations.yaml
media_player: !include media_player.yaml
script: !include scripts.yaml
notify: !include notify.yaml
shopping_list: !include shopping_list.yaml
zone: !include zones.yaml
panel_custom: !include panel_custom.yaml
binary_sensor: !include binary_sensors.yaml
camera: !include cameras.yaml
# Allows you to issue voice commands from the frontend in enabled browsers
conversation: !include conversations.yaml
zwave: !include zwave.yaml
shell_command: !include shell.yaml
switch: !include switch.yaml
input_boolean: !include input_boolean.yaml
alert: !include alert.yaml
input_number: !include input_number.yaml
history_graph: !include history_graph.yaml